### ISSUE TITLE
python encoder.py causes NameError: name 'model_flag' is not defined

### ISSUE THREAD

**Issue by yaoqi-zd** [ZhengxueCheng/Learned-Image-Compression-with-GMM-and-Attention#1]
Hi, thanks for sharing the code. When I run the 'python encoder.py', I encountered the following error message:
```
Traceback (most recent call last):
  File "encoder.py", line 27, in <module>
    main()
  File "encoder.py", line 23, in main
    compress(input, output, num_filters, checkpoint_dir)
  File "/home/yq223369/workspace/ImageCompression/GMMA-tf/network.py", line 572, in compress
    fileobj.write(np.array(model_flag, dtype=np.uint8).tobytes())

NameError: name 'model_flag' is not defined
```
I found in network.py, the variable 'model_flag' is indeed undefined, could you help me with this error?

**Comment by ZhengxueCheng** [comment]
Hi,
I update the network.py now, by just removing the line "fileobj.write(np.array(model_flag, dtype=np.uint8).tobytes())" in network.py, because model_flag was something to hand multiple checkpoints in previous versions. Now it should work.

**Comment by ZhengxueCheng** [comment]
> Hi, thanks for sharing the code. When I run the 'python encoder.py', I encountered the following error message:
> 
> ```
> Traceback (most recent call last):
>   File "encoder.py", line 27, in <module>
>     main()
>   File "encoder.py", line 23, in main
>     compress(input, output, num_filters, checkpoint_dir)
>   File "/home/yq223369/workspace/ImageCompression/GMMA-tf/network.py", line 572, in compress
>     fileobj.write(np.array(model_flag, dtype=np.uint8).tobytes())
> 
> NameError: name 'model_flag' is not defined
> ```
> 
> I found in network.py, the variable 'model_flag' is indeed undefined, could you help me with this error?

Hi, I update the network.py now, and encoder.py and decoder.py also have a small change. Please update three python files. 
If you have further questions, please let me know.

**Comment by yaoqi-zd** [comment]
@ZhengxueCheng thx, the codes now work properly!
